### ISSUE TITLE
Error when establishing singularity version

### ISSUE THREAD

**Issue by Peter-Kille** [Microbial-Ecology-Group/AMRplusplus#12]
I have attempted to install using singularity instructions and I get the following error either when using:
nextflow run main_AMR++.nf -profile singularity
or after manually downloading the singularity container and running:
nextflow run main_AMR++.nf -profile local -with-singularity amrplusplus_latest.sif

Error:

Unable to parse config file: '/home/peterkille/AMRplusplus/nextflow.config'

  Compile failed for sources FixedSetSources[name='/groovy/script/ScriptB6DED1A25169A5D2CA887C49E3310682']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  /groovy/script/ScriptB6DED1A25169A5D2CA887C49E3310682: 18: Unexpected input: '{' @ line 18, column 9.
     process {
             ^

  1 error

**Comment by EnriqueDoster** [comment]
Hello @Peter-Kille, 

Sorry for the inconvenience, but this was due to a simple error in the config file. Our latest update fixes this issue and should be ready for you to try. However, at this time we recommend installation with conda if that's possible. We find that singularity can still rely on server-side configuration. 

Thank you, please let us know if you run into any further issues. 

Best,
Enrique
