### ISSUE TITLE
SNPConfirmed matrix contains blank column in from AMR++ run

### ISSUE THREAD

**Issue by LLansing** [Microbial-Ecology-Group/AMRplusplus#9]
In my AMR++ run a single column corresponding to 1 of my input samples is blank in the SNPConfirmed result matrix. The sample name is empty in the header row and the AMR counts are missing for this column in all the subsequent rows, identified by two tab characters with nothing in between.

In the nextflow output the missing sample is show to have performed the runsnp step and there is no indication of error.

([Cross-posted from AMRplusplus_SNP](https://github.com/Isabella136/AmrPlusPlus_SNP/issues/22))

**Comment by Isabella136** [comment]
Update to this particular issue: https://github.com/Isabella136/AmrPlusPlus_SNP/issues/22

I suspect that the error comes from the `runsnp` process in the `resistome.nf` script. Since this issue doesn't seem to replicate exactly the same way, the error doesn't come from AmrPlusPlus_SNP (at least not individually). And because the previous version of the matrix is complete, we can assume that the error doesn't appear until reaching the `runsnp` process in the pipeline and how the pipeline transmits information to AmrPlusPlus_SNP. However, I still fail to see why this issue only occurs for a few samples.

**Comment by EnriqueDoster** [comment]
Hi @LLansing, we changed the way the SNPconfirmed counts are handled and this should have solved your problem. Please let us know if you run into further issues. If you still have your alignment bam files, you can run the resistome analysis using the following flags; `--pipeline bam_resistome --bam_files "/path/to/bam/*.bam"`.

Please let us know if you run into any issues!
